// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rdwhvrpzvfhkxygfjzkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkd2h2cnB6dmZoa3h5Z2Zqemt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTY2NzcsImV4cCI6MjA2NzczMjY3N30.tN9HwmuHHSzSDk3hewetqGPHdyzBabBVgDT66J9GRys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);